export const Languages = [
  { language: "af", name: "Afrikáans" },
  { language: "ar", name: "Arabe" },
  { language: "bg", name: "Bulgaro" },
  { language: "ca", name: "Catalan" },
  { language: "cy", name: "Gales" },
  { language: "da", name: "Danes" },
  { language: "de", name: "Aleman" },
  { language: "el", name: "Griego" },
  { language: "en", name: "Ingles" },
  { language: "es", name: "Español" },
  { language: "fa", name: "Persa" },
  { language: "fr", name: "Frances" },
  { language: "he", name: "Hebreo" },
  { language: "hi", name: "Hindi" },
  { language: "hr", name: "Croata" },
  { language: "hu", name: "Hungaro" },
  { language: "it", name: "Italiano" },
  { language: "ja", name: "Japones" },
  { language: "ko", name: "Koreano" },
  { language: "th", name: "Tailandés" },
];
